name: "Fanart"
guid: "170a157f-ac6c-437a-abdd-ca9c25cebd39"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-fanart.png"
version: "7"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Scrape poster images from Fanart"
description: "Scrape poster images for movies, shows, and artists in your library."
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Fanart.dll"
changelog: |-
  - Remove jQuery and update to es6 (#26) @grafixeyehero
  - chore(ci): builds, releas drafter and more (#22) @h1dden-da3m0n
  - Use System.Text.Json (#21) @Ullmie02

  ### New features and improvements ###
  - chore: plugin images (#25) @h1dden-da3m0n

  ### Dependency updates ###
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#23) @dependabot

  ### CI & build changes ###
  - Update ci (#27) @h1dden-da3m0n
